[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Tensorflow/blob/master/01_%ED%85%90%EC%84%9C%EA%B8%B0%EB%B3%B8.ipynb)

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
#그래프 생성
Graph1=tf.Graph()
with Graph1.as_default():
  x_vals=np.array([1.,3.,5.,7.,9.])

  m_placeholder=tf.placeholder(tf.float32)
  m_const=tf.constant(3.)
  m_variable=tf.Variable(30,name="sabum")

  init=tf.global_variables_initializer()
  my_product=tf.multiply(m_const, m_placeholder)  

In [16]:
#실행
with tf.Session(graph=Graph1) as sess:
  sess.run(init)
  print(sess.run(m_variable))

  for x_val in x_vals:
    print(sess.run(my_product, feed_dict={m_placeholder:x_val}))

30
3.0
9.0
15.0
21.0
27.0


In [0]:
Graph2=tf.Graph()
with Graph2.as_default():
  #배열의 크기를 모르면 None으로 설정한다.
  #특정값으로 설정했다면 반드시 동일한 사이즈의 데이터를 feed_dict에 전달해야 한다.
  x=tf.placeholder("float",[None,4])
  y=x*10+1

In [19]:
#placeholder에 값을 배정한 후 feed_dict에 저장한다.
with tf.Session(graph=Graph2) as sess:
  dataX=[[12,2,0,-2],[14,4,1,0]]
  placeX=sess.run(y, feed_dict={x:dataX})
  print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [30]:
#Fixed Tensor 만들기
sess=tf.Session()
A=sess.run(tf.zeros([2,3]))
B=sess.run(tf.ones([2,3]))
C=sess.run(tf.fill([2,3],13))
D=sess.run(tf.diag([4,-3,2]))
E=sess.run(tf.constant([5,2,4,2]))
print(A)
print(B)
print(C)
print(D)
print(E)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[13 13 13]
 [13 13 13]]
[[ 4  0  0]
 [ 0 -3  0]
 [ 0  0  2]]
[5 2 4 2]


In [37]:
#Sequence Tensor 만들기
#증분으로 sequence 텐서생성
G=sess.run(tf.range(start=6, limit=45, delta=3))

#동일 space으로 sequence 텐서생성
H=sess.run(tf.linspace(10.0, 92.0, 5))

#랜덤텐서 생성(일양분포)
i=sess.run(tf.random_uniform([2,3], minval=0, maxval=4))

#랜덤텐서 생성(정규분포)
j=sess.run(tf.random_normal([2,3], mean=5, stddev=4))

print(G)
print(H)
print(i)
print(j)

[ 6  9 12 15 18 21 24 27 30 33 36 39 42]
[10.  30.5 51.  71.5 92. ]
[[0.52761316 2.696848   1.0273495 ]
 [2.1780405  2.5636873  0.76131964]]
[[2.1166582  8.413364   5.4688516 ]
 [0.16143751 2.216009   2.8769934 ]]


In [39]:
#행렬 shuffle하기
k=sess.run(tf.diag([3,-2,4,5]))
k1=sess.run(tf.random_shuffle(k))

#sub행렬 가져오기
k2=sess.run(tf.random_crop(k1, [3,2]))

print(k1)
print(k2)

[[ 0  0  0  5]
 [ 3  0  0  0]
 [ 0 -2  0  0]
 [ 0  0  4  0]]
[[ 3  0]
 [ 0 -2]
 [ 0  0]]


In [52]:
#텐서 행렬연산
A=tf.random_uniform([3,2])
B=tf.fill([2,4],5.2)
C=tf.random_normal([3,4])
print(sess.run(B))

[[5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]]
[[0.90367746 0.1227808 ]
 [0.86408114 0.84864616]
 [0.16669023 0.8628353 ]]
[[1.4045324 2.3096175 4.011382  2.125338 ]
 [2.1531868 3.478814  3.8111572 3.2416196]
 [2.6330993 4.0676937 1.776639  2.0078225]]


In [56]:
#행렬곱 : matmul
#행렬합 : +
D=tf.matmul(A,B)+C
E=tf.add(tf.matmul(A,B),C)
print(sess.run(D))
print(sess.run(E))

[[6.069151  5.741364  6.2865076 4.4445405]
 [5.870769  4.3105183 6.0257072 4.12537  ]
 [4.380983  1.2766266 3.7189898 2.1187396]]
[[ 1.9637861  1.4915532  4.746661   2.606801 ]
 [ 1.72238    1.979518   2.7098851  2.1388354]
 [ 8.502008  10.028577  11.619692   9.604467 ]]


In [58]:
#활성화 함수(하이퍼볼릭 탄젠트, 시그모이드)
E=tf.nn.tanh([10,2,1,0.5,0.-0.5,-1.,-2.,-10.])
print(sess.run(E))

J=tf.nn.sigmoid([10,2,1,0.5,0,-0.5,-1,-2.,-10.])
print(sess.run(J))

[ 1.          0.9640276   0.7615942   0.46211717 -0.46211717 -0.7615942
 -0.9640276  -1.        ]
[9.9995458e-01 8.8079703e-01 7.3105860e-01 6.2245935e-01 5.0000000e-01
 3.7754068e-01 2.6894143e-01 1.1920292e-01 4.5397872e-05]


In [65]:
#활성화 함수(ReLU)
K1=sess.run(tf.nn.relu([-2.,1.,-3.,13.]))
K2=sess.run(tf.nn.relu6([-2.,1.,-3.,13.]))
print(K1)
print(K2)

[ 0.  1.  0. 13.]
[0. 1. 0. 6.]


In [64]:
#활성화 함수(Softplus)
K3=sess.run(tf.nn.softplus([-2.,1.,-3.,13.]))
print(K3)

[ 0.12692805  1.3132616   0.04858733 13.000002  ]


In [75]:
#활성화 함수(elu, relu6, softsign, softplus)
K4=sess.run(tf.nn.elu([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K4)
K5=sess.run(tf.nn.relu6([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K5)
K6=sess.run(tf.nn.softsign([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K6)
K7=sess.run(tf.nn.softplus([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K7)

[10.          2.          1.          0.5         0.         -0.39346933
 -0.63212055 -0.86466473 -0.9999546 ]
[6.  2.  1.  0.5 0.  0.  0.  0.  0. ]
[ 0.90909094  0.6666667   0.5         0.33333334  0.         -0.33333334
 -0.5        -0.6666667  -0.90909094]
[1.0000046e+01 2.1269281e+00 1.3132616e+00 9.7407699e-01 6.9314718e-01
 4.7407699e-01 3.1326163e-01 1.2692805e-01 4.5417706e-05]


/bin/sh: 1: /root/.jupyter/custom/custom.css: not found
