[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Tensorflow/blob/master/01_%ED%85%90%EC%84%9C%EA%B8%B0%EB%B3%B8.ipynb)

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
#그래프 생성
Graph1=tf.Graph()
with Graph1.as_default():
  x_vals=np.array([1.,3.,5.,7.,9.])

  m_placeholder=tf.placeholder(tf.float32)
  m_const=tf.constant(3.)
  m_variable=tf.Variable(30,name="sabum")

  init=tf.global_variables_initializer()
  my_product=tf.multiply(m_const, m_placeholder)  

In [16]:
#실행
with tf.Session(graph=Graph1) as sess:
  sess.run(init)
  print(sess.run(m_variable))

  for x_val in x_vals:
    print(sess.run(my_product, feed_dict={m_placeholder:x_val}))

30
3.0
9.0
15.0
21.0
27.0


In [0]:
Graph2=tf.Graph()
with Graph2.as_default():
  #배열의 크기를 모르면 None으로 설정한다.
  #특정값으로 설정했다면 반드시 동일한 사이즈의 데이터를 feed_dict에 전달해야 한다.
  x=tf.placeholder("float",[None,4])
  y=x*10+1

In [19]:
#placeholder에 값을 배정한 후 feed_dict에 저장한다.
with tf.Session(graph=Graph2) as sess:
  dataX=[[12,2,0,-2],[14,4,1,0]]
  placeX=sess.run(y, feed_dict={x:dataX})
  print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [30]:
#Fixed Tensor 만들기
sess=tf.Session()
A=sess.run(tf.zeros([2,3]))
B=sess.run(tf.ones([2,3]))
C=sess.run(tf.fill([2,3],13))
D=sess.run(tf.diag([4,-3,2]))
E=sess.run(tf.constant([5,2,4,2]))
print(A)
print(B)
print(C)
print(D)
print(E)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[13 13 13]
 [13 13 13]]
[[ 4  0  0]
 [ 0 -3  0]
 [ 0  0  2]]
[5 2 4 2]


In [37]:
#Sequence Tensor 만들기
#증분으로 sequence 텐서생성
G=sess.run(tf.range(start=6, limit=45, delta=3))

#동일 space으로 sequence 텐서생성
H=sess.run(tf.linspace(10.0, 92.0, 5))

#랜덤텐서 생성(일양분포)
i=sess.run(tf.random_uniform([2,3], minval=0, maxval=4))

#랜덤텐서 생성(정규분포)
j=sess.run(tf.random_normal([2,3], mean=5, stddev=4))

print(G)
print(H)
print(i)
print(j)

[ 6  9 12 15 18 21 24 27 30 33 36 39 42]
[10.  30.5 51.  71.5 92. ]
[[0.52761316 2.696848   1.0273495 ]
 [2.1780405  2.5636873  0.76131964]]
[[2.1166582  8.413364   5.4688516 ]
 [0.16143751 2.216009   2.8769934 ]]


In [39]:
#행렬 shuffle하기
k=sess.run(tf.diag([3,-2,4,5]))
k1=sess.run(tf.random_shuffle(k))

#sub행렬 가져오기
k2=sess.run(tf.random_crop(k1, [3,2]))

print(k1)
print(k2)

[[ 0  0  0  5]
 [ 3  0  0  0]
 [ 0 -2  0  0]
 [ 0  0  4  0]]
[[ 3  0]
 [ 0 -2]
 [ 0  0]]
