[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Tensorflow/blob/master/01_%ED%85%90%EC%84%9C%EA%B8%B0%EB%B3%B8.ipynb)

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
#그래프 생성
Graph1=tf.Graph()
with Graph1.as_default():
  x_vals=np.array([1.,3.,5.,7.,9.])

  m_placeholder=tf.placeholder(tf.float32)
  m_const=tf.constant(3.)
  m_variable=tf.Variable(30,name="sabum")

  init=tf.global_variables_initializer()
  my_product=tf.multiply(m_const, m_placeholder)  

In [6]:
#실행
with tf.Session(graph=Graph1) as sess:
  sess.run(init)
  print(sess.run(m_variable))

  for x_val in x_vals:
    print(sess.run(my_product, feed_dict={m_placeholder:x_val}))

30
3.0
9.0
15.0
21.0
27.0


In [0]:
Graph2=tf.Graph()
with Graph2.as_default():
  #배열의 크기를 모르면 None으로 설정한다.
  #특정값으로 설정했다면 반드시 동일한 사이즈의 데이터를 feed_dict에 전달해야 한다.
  x=tf.placeholder("float",[None,4])
  y=x*10+1

In [8]:
#placeholder에 값을 배정한 후 feed_dict에 저장한다.
with tf.Session(graph=Graph2) as sess:
  dataX=[[12,2,0,-2],[14,4,1,0]]
  placeX=sess.run(y, feed_dict={x:dataX})
  print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [9]:
#Fixed Tensor 만들기
sess=tf.Session()
A=sess.run(tf.zeros([2,3]))
B=sess.run(tf.ones([2,3]))
C=sess.run(tf.fill([2,3],13))
D=sess.run(tf.diag([4,-3,2]))
E=sess.run(tf.constant([5,2,4,2]))
print(A)
print(B)
print(C)
print(D)
print(E)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[13 13 13]
 [13 13 13]]
[[ 4  0  0]
 [ 0 -3  0]
 [ 0  0  2]]
[5 2 4 2]


In [10]:
#Sequence Tensor 만들기
#증분으로 sequence 텐서생성
G=sess.run(tf.range(start=6, limit=45, delta=3))

#동일 space으로 sequence 텐서생성
H=sess.run(tf.linspace(10.0, 92.0, 5))

#랜덤텐서 생성(일양분포)
i=sess.run(tf.random_uniform([2,3], minval=0, maxval=4))

#랜덤텐서 생성(정규분포)
j=sess.run(tf.random_normal([2,3], mean=5, stddev=4))

print(G)
print(H)
print(i)
print(j)

[ 6  9 12 15 18 21 24 27 30 33 36 39 42]
[10.  30.5 51.  71.5 92. ]
[[3.6422238  0.11219597 0.01660061]
 [1.250257   3.9856453  0.7761879 ]]
[[ 2.6518233   7.6606503  -0.08774853]
 [ 7.495042   12.057694    8.872282  ]]


In [11]:
#행렬 shuffle하기
k=sess.run(tf.diag([3,-2,4,5]))
k1=sess.run(tf.random_shuffle(k))

#sub행렬 가져오기
k2=sess.run(tf.random_crop(k1, [3,2]))

print(k1)
print(k2)

[[ 0 -2  0  0]
 [ 0  0  4  0]
 [ 0  0  0  5]
 [ 3  0  0  0]]
[[0 4]
 [0 0]
 [0 0]]


In [12]:
#텐서 행렬연산
A=tf.random_uniform([3,2])
B=tf.fill([2,4],5.2)
C=tf.random_normal([3,4])
print(sess.run(B))

[[5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2]]


In [13]:
#행렬곱 : matmul
#행렬합 : +
D=tf.matmul(A,B)+C
E=tf.add(tf.matmul(A,B),C)
print(sess.run(D))
print(sess.run(E))

[[3.4227536 3.1734653 2.821435  3.4394872]
 [6.6391673 7.756329  8.308286  7.510356 ]
 [5.7397456 3.9685118 4.5213957 6.5803633]]
[[7.484852  5.767562  5.772023  4.54004  ]
 [6.2904987 5.9996433 5.772556  5.9506173]
 [5.441549  4.805258  5.240522  5.266111 ]]


In [14]:
#활성화 함수(하이퍼볼릭 탄젠트, 시그모이드)
E=tf.nn.tanh([10,2,1,0.5,0.-0.5,-1.,-2.,-10.])
print(sess.run(E))

J=tf.nn.sigmoid([10,2,1,0.5,0,-0.5,-1,-2.,-10.])
print(sess.run(J))

[ 1.          0.9640276   0.7615942   0.46211717 -0.46211717 -0.7615942
 -0.9640276  -1.        ]
[9.9995458e-01 8.8079703e-01 7.3105860e-01 6.2245935e-01 5.0000000e-01
 3.7754068e-01 2.6894143e-01 1.1920292e-01 4.5397872e-05]


In [15]:
#활성화 함수(ReLU)
K1=sess.run(tf.nn.relu([-2.,1.,-3.,13.]))
K2=sess.run(tf.nn.relu6([-2.,1.,-3.,13.]))
print(K1)
print(K2)

[ 0.  1.  0. 13.]
[0. 1. 0. 6.]


In [16]:
#활성화 함수(Softplus)
K3=sess.run(tf.nn.softplus([-2.,1.,-3.,13.]))
print(K3)

[ 0.12692805  1.3132616   0.04858733 13.000002  ]


In [17]:
#활성화 함수(elu, relu6, softsign, softplus)
K4=sess.run(tf.nn.elu([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K4)
K5=sess.run(tf.nn.relu6([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K5)
K6=sess.run(tf.nn.softsign([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K6)
K7=sess.run(tf.nn.softplus([10, 2, 1, 0.5, 0, -0.5, -1., -2., -10.]))
print(K7)

[10.          2.          1.          0.5         0.         -0.39346933
 -0.63212055 -0.86466473 -0.9999546 ]
[6.  2.  1.  0.5 0.  0.  0.  0.  0. ]
[ 0.90909094  0.6666667   0.5         0.33333334  0.         -0.33333334
 -0.5        -0.6666667  -0.90909094]
[1.0000046e+01 2.1269281e+00 1.3132616e+00 9.7407699e-01 6.9314718e-01
 4.7407699e-01 3.1326163e-01 1.2692805e-01 4.5417706e-05]


In [28]:
#Loss Function에 대한 정의
#Loss Function
pred=np.asarray([0.2, 0.3, 0.5, 10.0, 12.0, 13.0, 3.5, 7.4, 3.9, 2.3])
actual=np.asarray([0.1, 0.4, 0.6, 9.0, 11.0, 12.0, 3.4, 7.1, 3.8, 2.0])
# x_val=tf.convert_to_tensor(pred)

#Loss Function : square
l2=tf.square(pred-actual)
l2_out=sess.run(tf.round(l2))
print(l2_out)

#Loss Funciton : abs
l1=tf.abs(pred-actual)
l1_out=sess.run(l1)
print(l1_out)

#sigmoid entropy
softmax_xentropy_variable=tf.nn.sigmoid_cross_entropy_with_logits(logits=l1_out, labels=l2_out)
print(sess.run(softmax_xentropy_variable))

[0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
[0.1 0.1 0.1 1.  1.  1.  0.1 0.3 0.1 0.3]
[0.74439666 0.74439666 0.74439666 0.31326169 0.31326169 0.31326169
 0.74439666 0.85435524 0.74439666 0.85435524]


In [0]:
x=tf.Variable(3, name='x', dtype=tf.float32)
log_x=tf.log(x)
log_x_squared=tf.square(x-4)  #log_x)

init=tf.global_variables_initializer()
optimizer=tf.train.GradientDescentOptimizer(0.7)
#optimizer=tf.train.AdamOptimizer(0.7)

#loss함수 : log_x_squared
#TensorFlow는 loss함수인 log_x_squared를 최소화하기 위해
#각 파라미터를 천천히 변경시켜 최적화하는 optimizer를 제공함
#여기서는 x가 해당 파라미터임
#tensor에는 다양한 optimizer함수가 있으며 
#이것을 이용하면 tensor가 알아서 loss fun값을 최소화하는 parameter를 구해줌
train=optimizer.minimize(log_x_squared)

In [74]:
with tf.Session() as sess:
  sess.run(init)
  a=sess.run(x)
  b=sess.run(log_x)
  c=sess.run(log_x_squared)
  
  print("x=" + str(a) + ", log_x="+ str(b) +", log_x_squared=" + str(c))
  
  for step in range(10):
    sess.run(train)
    print("Step=",step)
    print("x:",a)
    a=sess.run(x)
    print("loss fun. val:",sess.run(log_x_squared))
    

# init=tf.global_variables_initializer()

# with tf.Session() as sess:
#   sess.run(init)
#   print("starting at:", "x:", sess.run(x), "log(x)^2:",sess.run(log_x_squared))
#   for step in range(10):
#         sess.run(train)
#         print("step",step,"x:",sess.run(x),"log(x)^2:",sess.run(log_x_squared))

x=3.0, log_x=1.0986123, log_x_squared=1.0
('Step=', 0)
('x:', 3.0)
('loss fun. val:', 0.16000007)
('Step=', 1)
('x:', 4.4)
('loss fun. val:', 0.025600027)
('Step=', 2)
('x:', 3.84)
('loss fun. val:', 0.0040960168)
('Step=', 3)
('x:', 4.064)
('loss fun. val:', 0.0006553578)
('Step=', 4)
('x:', 3.9744)
('loss fun. val:', 0.000104859195)
('Step=', 5)
('x:', 4.01024)
('loss fun. val:', 1.677747e-05)
('Step=', 6)
('x:', 3.995904)
('loss fun. val:', 2.6843954e-06)
('Step=', 7)
('x:', 4.0016384)
('loss fun. val:', 4.2956577e-07)
('Step=', 8)
('x:', 3.9993446)
('loss fun. val:', 6.878054e-08)
('Step=', 9)
('x:', 4.0002623)
('loss fun. val:', 1.1004886e-08)
