[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Tensorflow/blob/master/QTable.ipynb)

In [3]:
!pip install gym


    100% |████████████████████████████████| 1.5MB 6.2MB/s 
    100% |████████████████████████████████| 1.0MB 8.2MB/s 
  Running setup.py bdist_wheel for gym ... - \ | / done
  Stored in directory: /root/.cache/pip/wheels/cb/14/71/f4ab006b1e6ff75c2b54985c2f98d0644fffe9c1dddc670925
Successfully built gym


In [0]:
import gym
import tensorflow as tf
import numpy as np

In [0]:
env = gym.make('FrozenLake-v0')

In [0]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)


In [9]:
print("Score over time: " +  str(sum(rList)/num_episodes))
print("Final Q-Table Values")
print(Q)

Score over time: 0.475
Final Q-Table Values
[[8.49842477e-02 8.59765904e-03 4.52719445e-03 7.66708687e-03]
 [1.88116098e-04 9.89540710e-04 1.27661125e-03 8.27746542e-03]
 [1.61751185e-03 1.71712517e-03 1.11423400e-02 3.06181136e-03]
 [2.73820631e-05 9.31273228e-04 9.83762926e-04 7.01586938e-03]
 [9.52202849e-02 1.75914523e-04 8.86716814e-04 1.59242296e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.61965392e-04 8.18337814e-08 5.13077533e-04 3.26857990e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.49877338e-03 5.72114576e-04 4.05873252e-03 1.21885000e-01]
 [2.32248030e-03 5.47824282e-02 1.99478975e-03 3.03285287e-03]
 [1.27825226e-01 1.17129406e-04 1.16058646e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.52013151e-01 8.31180973e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 6.49891116e-01]
 [0.0000000